basefolder.name=CucumberReports/ExtentReports
basefolder.datetimepattern=d-MMM-YY HH-mm-ss
extent.reporter.spark.start=true
extent.reporter.spark.out=CucumberExtentReport.html
screenshot.dir=screenshots
screenshot.rel.path=./screenshots/
